//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reserverProf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donnees
    {
        public int Id { get; set; }
        public System.DateTime dateConnexion { get; set; }
        public System.DateTime dateFinConnexion { get; set; }
        public Nullable<int> nbConnexion { get; set; }
        public Nullable<int> nbReservation { get; set; }
        public Nullable<int> nbParticipants { get; set; }
        public Nullable<int> nbCours { get; set; }
        public Nullable<int> nbGestionnaires { get; set; }
        public int gestionCompte_Id { get; set; }
        public int Abonnement_Id { get; set; }
    
        public virtual Abonnement Abonnement { get; set; }
        public virtual gestionCompte gestionCompte { get; set; }
    }
}
