//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reserverProf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> dateCours { get; set; }
        public Nullable<System.DateTime> horaireDebut { get; set; }
        public Nullable<System.DateTime> horaireFin { get; set; }
        public string commentaires { get; set; }
        public Nullable<int> matiere_Id { get; set; }
        public Nullable<int> statutRdv_Id { get; set; }
        public Nullable<int> jours_Id { get; set; }
        public Nullable<int> message_Id { get; set; }
        public Nullable<int> user_Id { get; set; }
    
        public virtual jours jours { get; set; }
        public virtual matiere matiere { get; set; }
        public virtual message message { get; set; }
        public virtual statutRdv statutRdv { get; set; }
        public virtual user user { get; set; }
    }
}
