//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reserverProf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int Id { get; set; }
        public System.DateTime dateCoursDebut { get; set; }
        public System.DateTime dateCoursFin { get; set; }
        public string commentaires { get; set; }
        public int matiere_Id { get; set; }
        public int statutRdv_Id { get; set; }
        public int jours_Id { get; set; }
        public int message_Id { get; set; }
        public int user_Id { get; set; }
    
        public virtual jours jours { get; set; }
        public virtual matiere matiere { get; set; }
        public virtual message message { get; set; }
        public virtual statutRdv statutRdv { get; set; }
        public virtual user user { get; set; }
    }
}
